### ISSUE TITLE
Extension takes 12s to activate

### ISSUE THREAD

**Issue by joyceerhl** [mjbvz/vscode-markdown-footnotes#10]
After cloning a repo, this extension takes 12s to activate (total initial extension activation time was 30s, so this extension accounted for over a third of that time). Since it looks like it doesn't declare a specific activation event I'm wondering if we can defer its activation or reduce the amount of work that happens in its `activate` method.

**Comment by mjbvz** [comment]
This extension sets `activationEvents: []` so it should never be explicitly activated, it is only activated when the built-in markdown extension calls in to it

Even if it were activated though, 12s seems suspect as the extension code is very simple: https://github.com/mjbvz/vscode-markdown-footnotes/blob/master/extension.js

Are we sure our monitoring process is correct here?
