### ISSUE TITLE
No preview in VS Code 1.29.1

### ISSUE THREAD

**Issue by clemensharten** [mjbvz/vscode-markdown-footnotes#4]
Since updating to the newest Version of VS Code (1.29.1), no preview can be displayed for markdown-files, when markdown-footnotes is enabled. 

This is true with and without other markdown-extensions like Markdown All in One enabled.

**Comment by mjbvz** [comment]
I can't repo this. What operating system are you on? Does this happen in VS Code insiders too?

**Comment by clemensharten** [comment]
It happen on Windows 10. I have now updated to VS Code Insiders, and the problem is gone. Thanks!
