### ISSUE TITLE
go to definition / go to usage

### ISSUE THREAD

**Issue by niderhoff** [mjbvz/vscode-markdown-footnotes#6]
Hello there,

for long documents it would be really nice if you could

* go to definition on the [^ft] marker to go the actualy footnote text
* do the reverse by if you are in the actualy footnote and cycle through all usages.

I will just put it here for later reference and might implement it myself at a later point in time if nobody else has.

Thanks for your extension by the way :)

**Comment by redactedscribe** [comment]
[vscode-markdown-footnote](https://github.com/houkanshan/vscode-markdown-footnote) is able to do this.
