### ISSUE TITLE
Please consider publishing the extension in open-vsx.org

### ISSUE THREAD

**Issue by lduktus** [mjbvz/vscode-markdown-footnotes#7]
This would make it more accessible for people using VSCodium and for some other Editors.
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by philoserf** [comment]
adding my voice to the plea

**Comment by philoserf** [comment]
https://github.com/HaaLeo/publish-vscode-extension

**Comment by mjbvz** [comment]
This is not worth it. One of my other extensions has 45 downloads on openvsix and 200,000+ on the official marketplace. I don't test on any editors besides VS Code either

**Comment by philoserf** [comment]
vscodium is vscode

**Comment by Morikko** [comment]
As an alternative available on Open VSX, you can use [Markdown Extended](https://open-vsx.org/extension/jebbs/markdown-extended) that includes `markdown-it-footnote` among others.
